services:
  drivenops_db:
    image: postgres
    container_name: drivenops_db
    restart: always 
    ports:
      - 4457:5432
    volumes:
      - pg:/var/lib/postgresql/d
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - drivenops_db 
    env_file:
      - .env.test

volumes:
  pg: